
class Constants:
    REWARD_SCALE_FACTOR = 10
    GREEN_CHAR_REWARD = 2 / REWARD_SCALE_FACTOR
    YELLOW_CHAR_REWARD = 1 / REWARD_SCALE_FACTOR
    GREY_CHAR_REWARD = 0 / REWARD_SCALE_FACTOR
    NEW_ROW_REWARD = -10 / REWARD_SCALE_FACTOR
    CORRECT_WORD_REWARD = 10 / REWARD_SCALE_FACTOR
    FAILED_GAME_REWARD = -10 / REWARD_SCALE_FACTOR
    NOT_WORD_LIST_REWARD = -1 / REWARD_SCALE_FACTOR
